site_name: dev-hackers подготовительные шаги.




site_url: https://dev-hackers.github.io/preparatory-steps/

nav:    
    - Главная:  index.md

    
        
    - Подготовительные действия:   
        - dev-hackers:
            - git старт: git_start/git-started.md
            #- Старт: dev-hackers/dev-hackers-start.md

    - Процесс обучения:
        - Начало с проекта:
            - Общее описание: working_process/start_working_process.md
            - По шагам учебный процесс: working_process/process_step_by_step.md
            - Order of Learning a Programming Language: working_process/order-learning-programming-lang.md


            

            #- Posts: v1/types/posts.m


markdown_extensions:

  
  
  - toc:
      permalink: True         
    

# сворачивание страниц
collapse_single_pages: true

    

theme: readthedocs

site_author:
    Валерий Бовсуновский  

    
    

    
    
   

